apiVersion: v1
kind: Secret
metadata:
  name: labwordpress-secret
  namespace: labwordpress
  labels: 
    app: wordpress
type: Opaque
data:
  mysql-root-username: d3BrdWJlcm5ldGVz
  mysql-root-password: d29yZHByZXNzODI0